### ISSUE TITLE
Bad datetime range in first setion of ce_383_00009_sections.json

### ISSUE THREAD

**Issue by emiliom** [nanoos-pnw/OOI#2]
@s-pearce I just noticed that in [ce_383_00009_sections.json](https://github.com/nanoos-pnw/OOI/blob/master/gliders/ce_383_00009_sections.json), the first section is obviously wrong. `datetime_end` is 13 hours **earlier** than `datetime_start`:

```json
{
  "datetime_start": "2020-02-20T20:31:00Z",
  "datetime_end": "2020-02-20T07:25:48Z",
  "direction": "W",
  "is_valid": true
}
```

**Comment by s-pearce** [comment]
Thanks Emilio,
I will check into what happened there.

Stuart

**Comment by emiliom** [comment]
Thanks. FYI I've already updated my code to handle the `is_valid` section flag and `datetime_end: null`. We're getting there.

**Comment by emiliom** [comment]
@s-pearce I decided to apply the fix myself now, b/c I'd like to test my code. So, I'm closing this issue. Thanks again.
